# - How to use:
#     python3 -m pip install pre-commit
#     pre-commit install --install hooks
# Upon a new commit - the hooks should automagically run
#
# - How to skip:
#     git commit --no-verify
# or
#     SKIP=fmt git commit
#     SKIP=cargo-check git commit

fail_fast: false
repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
    -   id: fmt
    -   id: cargo-check
