[package]
name = "pichu_bot"
version = "0.1.0"
edition = "2018"

[dependencies]
serenity = { version = "0.11", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
toml = "0.5.0"
serde = "1.0"

